namespace: manserfam

resources:
- ingress.yaml
- svc.yaml
- deploy.yaml

commonLabels:
  app: photos2022

images:
- name: jonas27/photos2022
  newTag: 0.1.2
  digest: sha256:65a554a12a6d1f5a802fa931205a2ea0d71bdff475ae24a555230ced0c6b69e2