helmGlobals:
  chartHome: "../../../charts/"

helmCharts:
- name: cert-manager
  includeCRDs: true
  namespace: cert-manager
  releaseName: cert-manager
  valuesFile: values.yaml
  # repo: https://charts.jetstack.io
  # version: v1.10.0

resources:
- cluster-issuer.yaml