apiVersion: apps/v1
kind: Deployment
metadata:
  name: isso
  namespace: katchblog
spec: 
  selector:
  replicas: 1
  template:
    metadata:
      labels:
        app: isso
    spec:
      containers:
      - name: isso
        image: ghcr.io/isso-comments/isso:latest
        args: ["/isso/bin/isso"]
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
          - mountPath: /db
            name: isso-storage
          - mountPath: /config/
            name: isso-config
      volumes:
      - name: isso-config
        configMap: 
          name: isso-config
      - name: isso-storage
        hostPath:
          path: "/volumes/katchblog/isso/isso-storage"
      restartPolicy: Always