apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-isso
  namespace: katchblog
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://katchblog.com"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - isso.katchblog.com
    - www.isso.katchblog.com
    secretName: isso-cert
  rules:
  - host: isso.katchblog.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: isso
            port: 
              name: http
