apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cert-manager
        namespace: cert-manager
        path: "ns/cert-manager/cert-manager"
        targetRevision: main

      - name: ingress-nginx
        namespace: ingress-nginx
        path: "ns/ingress-nginx/ingress-nginx"
        targetRevision: main

      - name: katchblog
        namespace: katchblog
        path: "ns/katchblog/katchblog"
        targetRevision: main
      - name: isso
        namespace: katchblog
        path: "ns/katchblog/isso"
        targetRevision: main
      
      - name: metrics-server
        namespace: kube-system
        path: "ns/kube-system/metrics-server"
        targetRevision: main
      
      - name: italy21
        namespace: manserfam
        path: "ns/manserfam/italy21"
        targetRevision: main
      - name: prewedding
        namespace: manserfam
        path: "ns/manserfam/prewedding"
        targetRevision: main
      - name: wedding
        namespace: manserfam
        path: "ns/manserfam/wedding"
        targetRevision: main

      - name: imagechecker
        namespace: tools
        path: "ns/tools/imagechecker"
        targetRevision: main


  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/jonas27/k8s-setup.git
        path: '{{path}}'
        targetRevision: '{{targetRevision}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true