apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cert-manager
        namespace: cert-manager
        path: "ns/cert-manager/cert-manager"
        targetRevision: main
      - name: katchblog
        namespace: katchblog
        path: "ns/katchblog/katchblog"
        targetRevision: main
      - name: isso
        namespace: katchblog
        path: "ns/katchblog/isso"
        targetRevision: main


  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/jonas27/k8s-setup.git
        path: '{{path}}'
        targetRevision: '{{targetRevision}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true