apiVersion: apps/v1
kind: Deployment
metadata:
  name: katchblog
  namespace: katchblog
spec: 
  replicas: 1
  template:
    spec:
      containers:
      - name: katchblog
        image: jonas27test/goserver@sha256:8ae229414f942ccfb7c531952bd4a929607d7a0db60746aefebc4ab02860620e
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
          - mountPath: /static
            name: katchblog-storage
      volumes:
      - name: katchblog-storage
        hostPath:
          path: "/volumes/katchblog/katchblog/"
      restartPolicy: Always