apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagechecker
  namespace: tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagechecker
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagechecker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imagechecker
subjects:
  - kind: ServiceAccount
    name: imagechecker
    namespace: tools