apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: master-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: k8sw
        namespace: argocd
        path: "ns/argocd/appsets"
        targetRevision: main

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/jonas27/k8s-setup.git
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=true