# https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#over-a-nodeport-service

namespace: nginx-ingress

helmGlobals:
  chartHome: "../../../charts/"

helmCharts:
- name: nginx-ingress
  includeCRDs: true
  namespace: nginx-ingress
  releaseName: nginx-ingress
  valuesFile: values.yaml
  # enable repo for new download
  # repo: https://helm.nginx.com/stable
